let tilesData = [
  {
    id: "basement-landing",
    name: "Basement Landing",
    type: "starting",
    floors: { basement: true, ground: false, upper: false },
    doors: ["top", "right", "bottom", "left"],
    image: "/images/basement-landing.png",
    row: 3,
    col: 3,
    message: "none",
  },
  {
    id: "entrance-hall",
    name: "Entrance Hall",
    type: "starting",
    floors: { basement: false, ground: true, upper: false },
    doors: ["top", "right", "left"],
    image: "/images/entrance-hall.png",
    row: 4,
    col: 3,
    message: "none",
  },
  {
    id: "hallway",
    name: "Hallway",
    type: "starting",
    floors: { basement: false, ground: true, upper: false },
    doors: ["top", "right", "bottom", "left"],
    image: "/images/hallway.png",
    row: 3,
    col: 3,
    message: `Leads to the Secret Stairs`,
  },
  {
    id: "ground-floor-staircase",
    name: "Ground Floor Staircase",
    type: "starting",
    floors: { basement: false, ground: true, upper: false },
    doors: ["bottom"],
    image: "/images/ground-floor-staircase.png",
    row: 2,
    col: 3,
    message: `Leads to the Upper Landing`,
  },
  {
    id: "upper-landing",
    name: "Upper Landing",
    type: "starting",
    floors: { basement: false, ground: false, upper: true },
    doors: ["top", "right", "bottom", "left"],
    image: "/images/upper-landing.png",
    row: 3,
    col: 3,
    message: `Leads to the Ground Floor Staircase`,
  },
  {
    id: "armory",
    name: "Armory",
    type: "discover",
    floors: { basement: true, ground: true, upper: false },
    doors: ["top", "right"],
    image: "/images/armory.png",
    symbol: "none",
    message: `When you discover this tile,
                            reveal cards from the top of the item deck until you reveal a weapon. <br>
                                Take it and bury the rest`,
  },
  {
    id: "ballroom",
    name: "Ballroom",
    type: "normal",
    floors: { basement: false, ground: true, upper: false },
    doors: ["top", "right", "bottom", "left"],
    image: "/images/ballroom.png",
    symbol: "omen",
    message: "none",
  },
  {
    id: "bloody-room",
    name: "Bloody Room",
    type: "normal",
    floors: { basement: false, ground: true, upper: true },
    doors: ["top", "right"],
    image: "/images/bloody-room.png",
    symbol: "item",
    message: "none",
  },
  {
    id: "catacombs",
    name: "Catacombs",
    type: "normal",
    floors: { basement: true, ground: false, upper: false },
    doors: ["top", "right", "bottom", "left"],
    image: "/images/catacombs.png",
    symbol: "omen",
    message: "none",
  },
  {
    id: "chapel",
    name: "Chapel",
    type: "discover",
    floors: { basement: false, ground: true, upper: false },
    doors: ["top", "bottom"],
    image: "/images/chapel.png",
    symbol: "omen",
    message: `When you discover this tile, gain 1 Sanity`,
  },
  {
    id: "charred-room",
    name: "Charred Room",
    type: "normal",
    floors: { basement: false, ground: true, upper: true },
    doors: ["top", "right"],
    image: "/images/charred-room.png",
    symbol: "omen",
    message: "none",
  },
  {
    id: "chasm",
    name: "Chasm",
    type: "normal",
    floors: { basement: true, ground: false, upper: false },
    doors: ["top", "bottom"],
    image: "/images/chasm.png",
    symbol: "event",
    message: "none",
  },
  {
    id: "collapsed-room",
    name: "Collapsed Room",
    type: "normal",
    floors: { basement: false, ground: true, upper: true },
    doors: ["top", "right"],
    image: "/images/collapsed-room.png",
    symbol: "none",
    message: `If you end your tur on this tile, make a speed roll. <br>
                            5+: Nothing happens. <br>
                            4-0: Place your explorer on the Basement Landing and take one die of Physical damage`,
  },
  {
    id: "conservatory",
    name: "Conservatory",
    type: "normal",
    floors: { basement: false, ground: true, upper: false },
    doors: ["top", "bottom"],
    image: "/images/conservatory.png",
    symbol: "item",
    message: "none",
  },
  {
    id: "cramped-passageway",
    name: "Cramped Passageway",
    type: "normal",
    floors: { basement: true, ground: true, upper: true },
    doors: ["top", "right", "bottom", "left"],
    image: "/images/cramped-passageway.png",
    symbol: "event",
    message: "none",
  },
  {
    id: "crawlspace",
    name: "Crawlspace",
    type: "normal",
    floors: { basement: true, ground: false, upper: true },
    doors: ["top", "right", "left"],
    image: "/images/crawlspace.png",
    symbol: "event",
    message: "none",
  },
  {
    id: "dining-room",
    name: "Dining Room",
    type: "normal",
    floors: { basement: false, ground: true, upper: false },
    doors: ["top", "right", "bottom", "left"],
    image: "/images/dining-room.png",
    symbol: "event",
    message: "none",
  },
  {
    id: "furnace-room",
    name: "Furnace Room",
    type: "normal",
    floors: { basement: true, ground: false, upper: false },
    doors: ["right", "bottom", "left"],
    image: "/images/furnace-room.png",
    symbol: "event",
    message: `If you end your turn on this tile, take one die of Physical damage`,
  },
  {
    id: "gallery",
    name: "Gallery",
    type: "normal",
    floors: { basement: false, ground: false, upper: true },
    doors: ["top", "bottom"],
    image: "/images/gallery.png",
    symbol: "event",
    message: `Leads to Ballroom`,
  },
  {
    id: "game-room",
    name: "Game Room",
    type: "normal",
    floors: { basement: true, ground: false, upper: true },
    doors: ["top", "right", "bottom", "left"],
    image: "/images/game-room.png",
    symbol: "item",
    message: "none",
  },
  {
    id: "graveyard",
    name: "Graveyard",
    type: "normal",
    floors: { basement: false, ground: true, upper: false },
    doors: ["top", "right"],
    image: "/images/graveyard.png",
    symbol: "omen",
    message: `Leads to the Underground Cavern`,
  },
  {
    id: "guest-quarters",
    name: "Guest Quarters",
    type: "normal",
    floors: { basement: false, ground: true, upper: true },
    doors: ["top", "right"],
    image: "/images/guest-quarters.png",
    symbol: "event",
    message: "none",
  },
  {
    id: "gymnasium",
    name: "Gymnasium",
    type: "discover",
    floors: { basement: true, ground: true, upper: false },
    doors: ["top", "left"],
    image: "/images/gymnasium.png",
    symbol: "none",
    message: `When you discover this tile, gain 1 Speed`,
  },
  {
    id: "junk-room",
    name: "Junk Room",
    type: "discover",
    floors: { basement: false, ground: true, upper: true },
    doors: ["top", "right", "bottom"],
    image: "/images/junk-room.png",
    symbol: "item",
    message: `When you discover this tile, place an Obstacle token on it`,
  },
  {
    id: "kitchen",
    name: "Kitchen",
    type: "normal",
    floors: { basement: false, ground: true, upper: false },
    doors: ["top", "bottom"],
    image: "/images/kitchen.png",
    symbol: "event",
    message: "none",
  },
  {
    id: "laboratory",
    name: "Laboratory",
    type: "normal",
    floors: { basement: false, ground: true, upper: false },
    doors: ["top", "right"],
    image: "/images/laboratory.png",
    symbol: "event",
    message: "none",
  },
  {
    id: "larder",
    name: "Larder",
    type: "discover",
    floors: { basement: false, ground: true, upper: false },
    doors: ["top", "left"],
    image: "/images/larder.png",
    symbol: "none",
    message: `When you discover this tile, gain 1 Might`,
  },
  {
    id: "laundry-chute",
    name: "Laundry Chute",
    type: "normal",
    floors: { basement: false, ground: true, upper: false },
    doors: ["top"],
    image: "/images/laundry-chute.png",
    symbol: "none",
    message: `Leads to the Basement Landing. <br>
                          If you end your turn on this tile,
                          place your explorer on the Basement Landing`,
  },
  {
    id: "library",
    name: "Library",
    type: "discover",
    floors: { basement: false, ground: true, upper: true },
    doors: ["top", "right", "bottom"],
    image: "/images/library.png",
    symbol: "omen",
    message: `When you discover this tile, gain 1 Knowledge`,
  },
  {
    id: "mystic-elevator",
    name: "Mystic Elevator",
    type: "normal",
    floors: { basement: true, ground: true, upper: true },
    doors: ["top"],
    image: "/images/mystic-elevator.png",
    symbol: "none",
    message: `Once per turn when you enter this tile, you may roll two dice.
                            Move the Mystic Elevator to an open doorway on: <br>
                            4+: Any region. <br>
                            3: Upper Floor. <br>
                            2: Ground Floor. <br>
                            1-0: Basement`,
  },
  {
    id: "nursery",
    name: "Nursery",
    type: "normal",
    floors: { basement: true, ground: true, upper: false },
    doors: ["top", "right"],
    image: "/images/nursery.png",
    symbol: "omen",
    message: "none",
  },
  {
    id: "observatory",
    name: "Observatory",
    type: "normal",
    floors: { basement: false, ground: false, upper: true },
    doors: ["top", "right", "bottom"],
    image: "/images/observatory.png",
    symbol: "omen",
    message: "none",
  },
  {
    id: "operating-theatre",
    name: "Operating Theatre",
    type: "normal",
    floors: { basement: true, ground: false, upper: true },
    doors: ["top", "right"],
    image: "/images/operating-theatre.png",
    symbol: "item",
    message: "none",
  },
  {
    id: "organ-room",
    name: "Organ Room",
    type: "normal",
    floors: { basement: true, ground: false, upper: true },
    doors: ["right", "bottom"],
    image: "/images/organ-room.png",
    symbol: "event",
    message: "none",
  },
  {
    id: "panic-room",
    name: "Panic Room",
    type: "discover",
    floors: { basement: true, ground: false, upper: false },
    doors: ["top"],
    image: "/images/panic-room.png",
    symbol: "omen",
    message: `When you discover this tile, if the Secret Stairs tile has not been placed, find it in the tile stack and place it in the Basement. Then, shuffle the tile stack.`,
  },
  {
    id: "primary-bedroom",
    name: "Primary Bedroom",
    type: "normal",
    floors: { basement: false, ground: true, upper: true },
    doors: ["top", "right", "bottom"],
    image: "/images/primary-bedroom.png",
    symbol: "omen",
    message: "none",
  },
  {
    id: "ritual-room",
    name: "Ritual Room",
    type: "normal",
    floors: { basement: true, ground: false, upper: false },
    doors: ["top", "right"],
    image: "/images/ritual-room.png",
    symbol: "omen",
    message: "none",
  },
  {
    id: "salon",
    name: "Salon",
    type: "normal",
    floors: { basement: false, ground: true, upper: true },
    doors: ["top", "right"],
    image: "/images/salon.png",
    symbol: "event",
    message: "none",
  },
  {
    id: "secret-staircase",
    name: "Secret Staircase",
    type: "normal",
    floors: { basement: true, ground: false, upper: false },
    doors: ["top"],
    image: "/images/secret-staircase.png",
    symbol: "none",
    message: `Leads to the Hallway`,
  },
  {
    id: "soundproofed-room",
    name: "Soundproofed Room",
    type: "normal",
    floors: { basement: true, ground: false, upper: true },
    doors: ["top", "right", "bottom"],
    image: "/images/soundproofed-room.png",
    symbol: "omen",
    message: "none",
  },
  {
    id: "specimen-room",
    name: "Specimen Room",
    type: "normal",
    floors: { basement: false, ground: true, upper: true },
    doors: ["right", "left"],
    image: "/images/specimen-room.png",
    symbol: "omen",
    message: "none",
  },
  {
    id: "statuary-corridor",
    name: "Statuary Corridor",
    type: "normal",
    floors: { basement: false, ground: false, upper: true },
    doors: ["top", "bottom"],
    image: "/images/statuary-corridor.png",
    symbol: "event",
    message: "none",
  },
  {
    id: "tower",
    name: "Tower",
    type: "normal",
    floors: { basement: false, ground: false, upper: true },
    doors: ["top", "bottom"],
    image: "/images/tower.png",
    symbol: "event",
    message: "none",
  },
  {
    id: "underground-cavern",
    name: "Underground Cavern",
    type: "normal",
    floors: { basement: true, ground: false, upper: false },
    doors: ["top", "right", "bottom", "left"],
    image: "/images/underground-cavern.png",
    symbol: "event",
    message: `Leads to the Graveyard`,
  },
  {
    id: "underground-lake",
    name: "Underground Lake",
    type: "normal",
    floors: { basement: true, ground: false, upper: false },
    doors: ["top", "right"],
    image: "/images/underground-lake.png",
    symbol: "event",
    message: "none",
  },
  {
    id: "vault",
    name: "Vault",
    type: "discover",
    floors: { basement: true, ground: false, upper: false },
    doors: ["top"],
    image: "/images/vault.png",
    symbol: "item",
    message: "none",
  },
  {
    id: "winter-bedroom",
    name: "Winter Bedroom",
    type: "normal",
    floors: { basement: false, ground: true, upper: true },
    doors: ["top", "right"],
    image: "/images/winter-bedroom.png",
    symbol: "omen",
    message: "none",
  },
];

export default tilesData;
